name: pytest
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
    paths:
      - 'tests/test_**.py'
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.event_name }} != 'pull_request'
      # Checkout pull request HEAD commit instead of merge commit
      #  https://github.com/marketplace/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
        if: ${{ github.event_name }} = 'pull_request'
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yapf
          pip install boto3
          pip install pytest
          pip install pytest-datadir
          pip install cloudinary
      - name: Run pytest
        run: |
          pytest -v
        working-directory: tests
