name: yamlfmt
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
    paths:
      - '**.yaml'
env:
  YAMLFMT_VER: 0.5.0
jobs:
  yamlfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.event_name }} != 'pull_request'
      # Checkout pull request HEAD commit instead of merge commit
      #  https://github.com/marketplace/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
        if: ${{ github.event_name }} = 'pull_request'
      - name: Install yamlfmt
        run: "wget https://github.com/google/yamlfmt/releases/download/v${{ env.YAMLFMT_VER }}/yamlfmt_${{ env.YAMLFMT_VER }}_Linux_x86_64.tar.gz\ntar xzvf yamlfmt_${{ env.YAMLFMT_VER }}_Linux_x86_64.tar.gz \n"
      - name: Run yamlfmt
        run: |
          ./yamlfmt -lint
